#!/usr/libexec/atf-sh

: ${TMPDIR=/tmp}

. $(atf_get_srcdir)/../../scripts/utils.subr

atf_test_case start_stopped cleanup

start_stopped_head()
{
	atf_set descr "stroke:start_stopped"
	atf_set require.user root
}

start_stopped_body()
{
	sst_init_stroke moon

	sst_check_service_start_stopped moon strongswan \
		-e match:"Starting strongSwan"
}

start_stopped_cleanup()
{
	sst_cleanup
}

atf_test_case start_started cleanup

start_started_head()
{
	atf_set descr "stroke:start_started"
	atf_set require.user root
}

start_started_body()
{
	sst_init_stroke moon

	sst_check_service_start_started moon strongswan
}

start_started_cleanup()
{
	sst_cleanup
}

atf_test_case stop_stopped cleanup

stop_stopped_head()
{
	atf_set descr "stroke:stop_stopped"
	atf_set require.user root
}

stop_stopped_body()
{
	sst_init_stroke moon

	sst_check_service_stop_stopped moon strongswan
}

stop_stopped_cleanup()
{
	sst_cleanup
}

atf_test_case stop_started cleanup

stop_started_head()
{
	atf_set descr "stroke:stop_started"
	atf_set require.user root
}

stop_started_body()
{
	sst_init_stroke moon

	sst_check_service_stop_started moon strongswan
}

stop_started_cleanup()
{
	sst_cleanup
}

atf_test_case restart_stopped cleanup

restart_stopped_head()
{
	atf_set descr "stroke:restart_stopped"
	atf_set require.user root
}

restart_stopped_body()
{
	sst_init_stroke moon

	sst_check_service_restart_stopped moon strongswan \
		-e match:"Starting strongSwan"
}

restart_stopped_cleanup()
{
	sst_cleanup
}

atf_test_case restart_started cleanup

restart_started_head()
{
	atf_set descr "stroke:restart_started"
	atf_set require.user root
}

restart_started_body()
{
	sst_init_stroke moon

	sst_check_service_restart_started moon strongswan \
		-e match:"Starting strongSwan"
}

restart_started_cleanup()
{
	sst_cleanup
}

atf_test_case status_stopped cleanup

status_stopped_head()
{
	atf_set descr "stroke:status_stopped"
	atf_set require.user root
}

status_stopped_body()
{
	sst_init_stroke moon

	sst_check_service_status_stopped moon strongswan
}

status_stopped_cleanup()
{
	sst_cleanup
}

atf_test_case status_started cleanup

status_started_head()
{
	atf_set descr "stroke:status_started"
	atf_set require.user root
}

status_started_body()
{
	sst_init_stroke moon

	sst_check_service_status_started moon strongswan \
		-o match:"Security Associations"
}

status_started_cleanup()
{
	sst_cleanup
}

atf_test_case statusall_stopped cleanup

statusall_stopped_head()
{
	atf_set descr "stroke:statusall_stopped"
	atf_set require.user root
}

statusall_stopped_body()
{
	sst_init_stroke moon

	sst_check_service_statusall_stopped moon strongswan
}

statusall_stopped_cleanup()
{
	sst_cleanup
}

atf_test_case statusall_started cleanup

statusall_started_head()
{
	atf_set descr "stroke:statusall_started"
	atf_set require.user root
}

statusall_started_body()
{
	sst_init_stroke moon

	sst_check_service_statusall_started moon strongswan \
		-o match:"Status of IKE charon daemon" \
		-o match:"Connections" \
		-o match:"Security Associations"
}

statusall_started_cleanup()
{
	sst_cleanup
}

atf_test_case reload_stopped cleanup

reload_stopped_head()
{
	atf_set descr "stroke:reload_stopped"
	atf_set require.user root
}

reload_stopped_body()
{
	sst_init_stroke moon

	sst_check_service_reload_stopped moon strongswan \
		-e match:"starter is not running"
}

reload_stopped_cleanup()
{
	sst_cleanup
}

atf_test_case reload_started cleanup

reload_started_head()
{
	atf_set descr "stroke:reload_started"
	atf_set require.user root
}

reload_started_body()
{
	sst_init_stroke moon

	sst_check_service_reload_started moon strongswan \
		-e match:"Reloading strongSwan IPsec configuration..."
}

reload_started_cleanup()
{
	sst_cleanup
}

atf_test_case sigkill cleanup

sigkill_head()
{
	atf_set descr "stroke:sigkill"
	atf_set require.user root
}

sigkill_body()
{
	sst_init_stroke moon

	service -j moon strongswan start
	jexec moon sleep 1

	charon_pid=$(jexec moon cat /var/run/charon.pid)
	jexec moon kill -9 $charon_pid
	jexec moon sleep 5

	atf_check \
		-o match:"/usr/local/libexec/ipsec/charon" \
		ps auxww -J moon
}

sigkill_cleanup()
{
	sst_cleanup
}

atf_init_test_cases()
{
	atf_add_test_case start_stopped
	atf_add_test_case start_started
	atf_add_test_case stop_stopped
	atf_add_test_case stop_started
	atf_add_test_case restart_stopped
	atf_add_test_case restart_started
	atf_add_test_case status_stopped
	atf_add_test_case status_started
	atf_add_test_case statusall_stopped
	atf_add_test_case statusall_started
	atf_add_test_case reload_stopped
	atf_add_test_case reload_started
	atf_add_test_case sigkill
}
